name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-analyze:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '>=3.3.3 <4.0.0'

      # Step 3: Verify Flutter installation
      - name: Verify Flutter Installation
        run: flutter --version

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 5: Analyze code
      - name: Run Static Code Analysis
        run: flutter analyze

      # Step 6: Run tests
      - name: Run Tests
        run: flutter test

      # Step 7: Build APK
      - name: Build APK
        run: flutter build apk --release
